using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Refazer.Web.Models
{
    /// <summary>
    /// Class tha represents a transformation generated by Refazer
    /// </summary>
    public class Transformation
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { set; get; }

        [Required]
        public string Program { set; get; }

        [Required]
        public string Examples { set; get; }

        [Required, DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime Time { set; get; }

        public int Rank { set; get; }

        public int RankType { set; get; }
        [Required]
        public int SessionId { set; get; }
    }
}