using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Refazer.WebAPI.Models
{
    /// <summary>
    /// Class tha represents a transformation generated by Refazer
    /// </summary>
    public class Transformation2
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { set; get; }

        [Required, DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime Time { set; get; }

        [Required]
        public String EndPoint { get; set; }

        [ForeignKey("EndPoint")]
        public Assignment Assignment { get; set; }

        [Required]
        public string IncorrectCode { set; get; }

        [Required]
        public string CorrectCode { set; get; }

        [Required]
        public string Program { set; get; }

        public int Rank { set; get; }

        public int RankType { set; get; }
    }
}