//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ECMAScriptCSharpTarget.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IECMAScriptCSharpTargetListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class ECMAScriptCSharpTargetBaseListener : IECMAScriptCSharpTargetListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ECMAScriptCSharpTargetParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ECMAScriptCSharpTargetParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.sourceElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceElements([NotNull] ECMAScriptCSharpTargetParser.SourceElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.sourceElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceElements([NotNull] ECMAScriptCSharpTargetParser.SourceElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.sourceElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceElement([NotNull] ECMAScriptCSharpTargetParser.SourceElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.sourceElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceElement([NotNull] ECMAScriptCSharpTargetParser.SourceElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ECMAScriptCSharpTargetParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ECMAScriptCSharpTargetParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] ECMAScriptCSharpTargetParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] ECMAScriptCSharpTargetParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] ECMAScriptCSharpTargetParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] ECMAScriptCSharpTargetParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableStatement([NotNull] ECMAScriptCSharpTargetParser.VariableStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableStatement([NotNull] ECMAScriptCSharpTargetParser.VariableStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationList([NotNull] ECMAScriptCSharpTargetParser.VariableDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationList([NotNull] ECMAScriptCSharpTargetParser.VariableDeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] ECMAScriptCSharpTargetParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] ECMAScriptCSharpTargetParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.initialiser"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialiser([NotNull] ECMAScriptCSharpTargetParser.InitialiserContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.initialiser"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialiser([NotNull] ECMAScriptCSharpTargetParser.InitialiserContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.emptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] ECMAScriptCSharpTargetParser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.emptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] ECMAScriptCSharpTargetParser.EmptyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] ECMAScriptCSharpTargetParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] ECMAScriptCSharpTargetParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] ECMAScriptCSharpTargetParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] ECMAScriptCSharpTargetParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoStatement([NotNull] ECMAScriptCSharpTargetParser.DoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoStatement([NotNull] ECMAScriptCSharpTargetParser.DoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] ECMAScriptCSharpTargetParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] ECMAScriptCSharpTargetParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] ECMAScriptCSharpTargetParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] ECMAScriptCSharpTargetParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForVarStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForVarStatement([NotNull] ECMAScriptCSharpTargetParser.ForVarStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForVarStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForVarStatement([NotNull] ECMAScriptCSharpTargetParser.ForVarStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForInStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInStatement([NotNull] ECMAScriptCSharpTargetParser.ForInStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForInStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInStatement([NotNull] ECMAScriptCSharpTargetParser.ForInStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForVarInStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForVarInStatement([NotNull] ECMAScriptCSharpTargetParser.ForVarInStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForVarInStatement</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForVarInStatement([NotNull] ECMAScriptCSharpTargetParser.ForVarInStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] ECMAScriptCSharpTargetParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] ECMAScriptCSharpTargetParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] ECMAScriptCSharpTargetParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] ECMAScriptCSharpTargetParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] ECMAScriptCSharpTargetParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] ECMAScriptCSharpTargetParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.withStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithStatement([NotNull] ECMAScriptCSharpTargetParser.WithStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.withStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithStatement([NotNull] ECMAScriptCSharpTargetParser.WithStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] ECMAScriptCSharpTargetParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] ECMAScriptCSharpTargetParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseBlock([NotNull] ECMAScriptCSharpTargetParser.CaseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseBlock([NotNull] ECMAScriptCSharpTargetParser.CaseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseClauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseClauses([NotNull] ECMAScriptCSharpTargetParser.CaseClausesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseClauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseClauses([NotNull] ECMAScriptCSharpTargetParser.CaseClausesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseClause([NotNull] ECMAScriptCSharpTargetParser.CaseClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.caseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseClause([NotNull] ECMAScriptCSharpTargetParser.CaseClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.defaultClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultClause([NotNull] ECMAScriptCSharpTargetParser.DefaultClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.defaultClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultClause([NotNull] ECMAScriptCSharpTargetParser.DefaultClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.labelledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelledStatement([NotNull] ECMAScriptCSharpTargetParser.LabelledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.labelledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelledStatement([NotNull] ECMAScriptCSharpTargetParser.LabelledStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.throwStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowStatement([NotNull] ECMAScriptCSharpTargetParser.ThrowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.throwStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowStatement([NotNull] ECMAScriptCSharpTargetParser.ThrowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.tryStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryStatement([NotNull] ECMAScriptCSharpTargetParser.TryStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.tryStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryStatement([NotNull] ECMAScriptCSharpTargetParser.TryStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.catchProduction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchProduction([NotNull] ECMAScriptCSharpTargetParser.CatchProductionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.catchProduction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchProduction([NotNull] ECMAScriptCSharpTargetParser.CatchProductionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.finallyProduction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinallyProduction([NotNull] ECMAScriptCSharpTargetParser.FinallyProductionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.finallyProduction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinallyProduction([NotNull] ECMAScriptCSharpTargetParser.FinallyProductionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.debuggerStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebuggerStatement([NotNull] ECMAScriptCSharpTargetParser.DebuggerStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.debuggerStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebuggerStatement([NotNull] ECMAScriptCSharpTargetParser.DebuggerStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] ECMAScriptCSharpTargetParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] ECMAScriptCSharpTargetParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] ECMAScriptCSharpTargetParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] ECMAScriptCSharpTargetParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionBody([NotNull] ECMAScriptCSharpTargetParser.FunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionBody([NotNull] ECMAScriptCSharpTargetParser.FunctionBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] ECMAScriptCSharpTargetParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] ECMAScriptCSharpTargetParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.elementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementList([NotNull] ECMAScriptCSharpTargetParser.ElementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.elementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementList([NotNull] ECMAScriptCSharpTargetParser.ElementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.elision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElision([NotNull] ECMAScriptCSharpTargetParser.ElisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.elision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElision([NotNull] ECMAScriptCSharpTargetParser.ElisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.objectLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectLiteral([NotNull] ECMAScriptCSharpTargetParser.ObjectLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.objectLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectLiteral([NotNull] ECMAScriptCSharpTargetParser.ObjectLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertyNameAndValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyNameAndValueList([NotNull] ECMAScriptCSharpTargetParser.PropertyNameAndValueListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertyNameAndValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyNameAndValueList([NotNull] ECMAScriptCSharpTargetParser.PropertyNameAndValueListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PropertyExpressionAssignment</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyExpressionAssignment([NotNull] ECMAScriptCSharpTargetParser.PropertyExpressionAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PropertyExpressionAssignment</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyExpressionAssignment([NotNull] ECMAScriptCSharpTargetParser.PropertyExpressionAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PropertyGetter</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyGetter([NotNull] ECMAScriptCSharpTargetParser.PropertyGetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PropertyGetter</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyGetter([NotNull] ECMAScriptCSharpTargetParser.PropertyGetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PropertySetter</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertySetter([NotNull] ECMAScriptCSharpTargetParser.PropertySetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PropertySetter</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.propertyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertySetter([NotNull] ECMAScriptCSharpTargetParser.PropertySetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] ECMAScriptCSharpTargetParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] ECMAScriptCSharpTargetParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertySetParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertySetParameterList([NotNull] ECMAScriptCSharpTargetParser.PropertySetParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.propertySetParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertySetParameterList([NotNull] ECMAScriptCSharpTargetParser.PropertySetParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] ECMAScriptCSharpTargetParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] ECMAScriptCSharpTargetParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] ECMAScriptCSharpTargetParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] ECMAScriptCSharpTargetParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.expressionSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionSequence([NotNull] ECMAScriptCSharpTargetParser.ExpressionSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.expressionSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionSequence([NotNull] ECMAScriptCSharpTargetParser.ExpressionSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TernaryExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernaryExpression([NotNull] ECMAScriptCSharpTargetParser.TernaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TernaryExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernaryExpression([NotNull] ECMAScriptCSharpTargetParser.TernaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAndExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] ECMAScriptCSharpTargetParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAndExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] ECMAScriptCSharpTargetParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreIncrementExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIncrementExpression([NotNull] ECMAScriptCSharpTargetParser.PreIncrementExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreIncrementExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIncrementExpression([NotNull] ECMAScriptCSharpTargetParser.PreIncrementExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectLiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.ObjectLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectLiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.ObjectLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInExpression([NotNull] ECMAScriptCSharpTargetParser.InExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInExpression([NotNull] ECMAScriptCSharpTargetParser.InExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] ECMAScriptCSharpTargetParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] ECMAScriptCSharpTargetParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpression([NotNull] ECMAScriptCSharpTargetParser.NotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpression([NotNull] ECMAScriptCSharpTargetParser.NotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreDecreaseExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreDecreaseExpression([NotNull] ECMAScriptCSharpTargetParser.PreDecreaseExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreDecreaseExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreDecreaseExpression([NotNull] ECMAScriptCSharpTargetParser.PreDecreaseExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArgumentsExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentsExpression([NotNull] ECMAScriptCSharpTargetParser.ArgumentsExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArgumentsExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentsExpression([NotNull] ECMAScriptCSharpTargetParser.ArgumentsExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisExpression([NotNull] ECMAScriptCSharpTargetParser.ThisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisExpression([NotNull] ECMAScriptCSharpTargetParser.ThisExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionExpression([NotNull] ECMAScriptCSharpTargetParser.FunctionExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionExpression([NotNull] ECMAScriptCSharpTargetParser.FunctionExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinusExpression([NotNull] ECMAScriptCSharpTargetParser.UnaryMinusExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinusExpression([NotNull] ECMAScriptCSharpTargetParser.UnaryMinusExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] ECMAScriptCSharpTargetParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] ECMAScriptCSharpTargetParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PostDecreaseExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostDecreaseExpression([NotNull] ECMAScriptCSharpTargetParser.PostDecreaseExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PostDecreaseExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostDecreaseExpression([NotNull] ECMAScriptCSharpTargetParser.PostDecreaseExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeofExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeofExpression([NotNull] ECMAScriptCSharpTargetParser.TypeofExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeofExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeofExpression([NotNull] ECMAScriptCSharpTargetParser.TypeofExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InstanceofExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceofExpression([NotNull] ECMAScriptCSharpTargetParser.InstanceofExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InstanceofExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceofExpression([NotNull] ECMAScriptCSharpTargetParser.InstanceofExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlusExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryPlusExpression([NotNull] ECMAScriptCSharpTargetParser.UnaryPlusExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlusExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryPlusExpression([NotNull] ECMAScriptCSharpTargetParser.UnaryPlusExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DeleteExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteExpression([NotNull] ECMAScriptCSharpTargetParser.DeleteExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DeleteExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteExpression([NotNull] ECMAScriptCSharpTargetParser.DeleteExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualityExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] ECMAScriptCSharpTargetParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualityExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] ECMAScriptCSharpTargetParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitXOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitXOrExpression([NotNull] ECMAScriptCSharpTargetParser.BitXOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitXOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitXOrExpression([NotNull] ECMAScriptCSharpTargetParser.BitXOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicativeExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] ECMAScriptCSharpTargetParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicativeExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] ECMAScriptCSharpTargetParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitShiftExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitShiftExpression([NotNull] ECMAScriptCSharpTargetParser.BitShiftExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitShiftExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitShiftExpression([NotNull] ECMAScriptCSharpTargetParser.BitShiftExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenthesizedExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedExpression([NotNull] ECMAScriptCSharpTargetParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenthesizedExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedExpression([NotNull] ECMAScriptCSharpTargetParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditiveExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] ECMAScriptCSharpTargetParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditiveExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] ECMAScriptCSharpTargetParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RelationalExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] ECMAScriptCSharpTargetParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RelationalExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] ECMAScriptCSharpTargetParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PostIncrementExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostIncrementExpression([NotNull] ECMAScriptCSharpTargetParser.PostIncrementExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PostIncrementExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostIncrementExpression([NotNull] ECMAScriptCSharpTargetParser.PostIncrementExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitNotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitNotExpression([NotNull] ECMAScriptCSharpTargetParser.BitNotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitNotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitNotExpression([NotNull] ECMAScriptCSharpTargetParser.BitNotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewExpression([NotNull] ECMAScriptCSharpTargetParser.NewExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewExpression([NotNull] ECMAScriptCSharpTargetParser.NewExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayLiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.ArrayLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayLiteralExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteralExpression([NotNull] ECMAScriptCSharpTargetParser.ArrayLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberDotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDotExpression([NotNull] ECMAScriptCSharpTargetParser.MemberDotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberDotExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDotExpression([NotNull] ECMAScriptCSharpTargetParser.MemberDotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberIndexExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberIndexExpression([NotNull] ECMAScriptCSharpTargetParser.MemberIndexExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberIndexExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberIndexExpression([NotNull] ECMAScriptCSharpTargetParser.MemberIndexExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierExpression([NotNull] ECMAScriptCSharpTargetParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierExpression([NotNull] ECMAScriptCSharpTargetParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitAndExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitAndExpression([NotNull] ECMAScriptCSharpTargetParser.BitAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitAndExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitAndExpression([NotNull] ECMAScriptCSharpTargetParser.BitAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitOrExpression([NotNull] ECMAScriptCSharpTargetParser.BitOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitOrExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitOrExpression([NotNull] ECMAScriptCSharpTargetParser.BitOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentOperatorExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperatorExpression([NotNull] ECMAScriptCSharpTargetParser.AssignmentOperatorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentOperatorExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperatorExpression([NotNull] ECMAScriptCSharpTargetParser.AssignmentOperatorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VoidExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoidExpression([NotNull] ECMAScriptCSharpTargetParser.VoidExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VoidExpression</c>
	/// labeled alternative in <see cref="ECMAScriptCSharpTargetParser.singleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoidExpression([NotNull] ECMAScriptCSharpTargetParser.VoidExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperator([NotNull] ECMAScriptCSharpTargetParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperator([NotNull] ECMAScriptCSharpTargetParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] ECMAScriptCSharpTargetParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] ECMAScriptCSharpTargetParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.numericLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericLiteral([NotNull] ECMAScriptCSharpTargetParser.NumericLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.numericLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericLiteral([NotNull] ECMAScriptCSharpTargetParser.NumericLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.identifierName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierName([NotNull] ECMAScriptCSharpTargetParser.IdentifierNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.identifierName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierName([NotNull] ECMAScriptCSharpTargetParser.IdentifierNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.reservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReservedWord([NotNull] ECMAScriptCSharpTargetParser.ReservedWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.reservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReservedWord([NotNull] ECMAScriptCSharpTargetParser.ReservedWordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] ECMAScriptCSharpTargetParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] ECMAScriptCSharpTargetParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.futureReservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFutureReservedWord([NotNull] ECMAScriptCSharpTargetParser.FutureReservedWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.futureReservedWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFutureReservedWord([NotNull] ECMAScriptCSharpTargetParser.FutureReservedWordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.getter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetter([NotNull] ECMAScriptCSharpTargetParser.GetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.getter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetter([NotNull] ECMAScriptCSharpTargetParser.GetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.setter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetter([NotNull] ECMAScriptCSharpTargetParser.SetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.setter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetter([NotNull] ECMAScriptCSharpTargetParser.SetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEos([NotNull] ECMAScriptCSharpTargetParser.EosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEos([NotNull] ECMAScriptCSharpTargetParser.EosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.eof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEof([NotNull] ECMAScriptCSharpTargetParser.EofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ECMAScriptCSharpTargetParser.eof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEof([NotNull] ECMAScriptCSharpTargetParser.EofContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
