// <auto-generated />
namespace Refazer.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestCasesRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestCasesRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201708150026306_TestCasesRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
