// <auto-generated />
namespace Refazer.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingranktype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingranktype));
        
        string IMigrationMetadata.Id
        {
            get { return "201610222142595_adding-rank~-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
